cache_dir: cache

# StyleGAN2
size: 1024
ckpt: Barbershop/pretrained_models/ffhq.pt
channel_multiplier: 2
latent: 512
n_mlp: 8

# Arguments
device: cuda
seed: 1234
tile_latent: False
opt_name: adam
learning_rate: 0.01
lr_schedule: fixed
save_intermediate: False
save_interval: 300
verbose: False
seg_ckpt: Barbershop/pretrained_models/seg.pth

# Embedding loss options
percept_lambda: 1.0
l2_lambda: 1.0
p_norm_lambda: 0.001
l_F_lambda: 0.1
W_steps: 300
FS_steps: 250


encoder_weight_path: ./HairMapper/ckpts/e4e_ffhq_encode.pt